apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
apiServerCertSANs:
- "127.0.0.1"
- "$my_master_ip"
- "$load_balancer_ip"
controlPlaneEndpoint: "$load_balancer_ip"
etcd:
$ENDPOINTS_LINES
networking:
  podSubnet: $my_KUBE_CIDR
